### ISSUE TITLE
bug: error during installation with Python 3.10

### ISSUE THREAD

**Issue by jthegedus** [jthegedus/asdf-gcloud#52]
### Describe the bug

Python 3.10 causes the `gcloud` installation script to fail

### Steps to reproduce

1. asdf install python 3.10.0
2. asdf local python 3.10.0
3. asdf install gcloud latest

```
➜ asdf install gcloud latest
⏬  downloading google-cloud-sdk-360.0.0-linux-x86_64.tar.gz
################################################################################################################## 100.0%
✅  downloaded!
✅  All dependencies found on system!
📦  extracting...
✅  extracted!
🚧  installing...
Welcome to the Google Cloud SDK!
Traceback (most recent call last):
  File "/home/jthegedus/.asdf/installs/gcloud/360.0.0/bin/bootstrapping/install.py", line 12, in <module>
    import bootstrapping
  File "/home/jthegedus/.asdf/installs/gcloud/360.0.0/bin/bootstrapping/bootstrapping.py", line 46, in <module>
    from googlecloudsdk.core.updater import update_manager
  File "/home/jthegedus/.asdf/installs/gcloud/360.0.0/lib/googlecloudsdk/core/updater/update_manager.py", line 39, in <module>
    from googlecloudsdk.core.console import progress_tracker
  File "/home/jthegedus/.asdf/installs/gcloud/360.0.0/lib/googlecloudsdk/core/console/progress_tracker.py", line 651, in <module>
    class _BaseStagedProgressTracker(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```

### asdf version

v0.8.1-a1ef92a

### asdf-gcloud version

1.1.0

### gcloud version

360.0.0

**Comment by jthegedus** [comment]
No one else has raised this, so it may be a transient issue. Closing for now unless it comes up again.
